# <p>Pentagonal numbers are generated by the formula, $P_n=n(3n-1)/2$. The first ten pentagonal numbers are:
# $$1, 5, 12, 22, 35, 51, 70, 92, 117, 145, \dots$$</p>
# <p>It can be seen that $P_4 + P_7 = 22 + 70 = 92 = P_8$. However, their difference, $70 - 22 = 48$, is not pentagonal.</p>
# <p>Find the pair of pentagonal numbers, $P_j$ and $P_k$, for which their sum and difference are pentagonal and $D = |P_k - P_j|$ is minimised; what is the value of $D$?</p>

from math import sqrt
import time

def P(n):
    return n*(3*n-1)/2

def inv_P(p):
    return (1 + sqrt(1+24*p)) % 6 == 0

start = time.time()
p_list = []
for n in range(1, 10001):
    p_list.append(P(n))

for i in range(10_000):
    for j in reversed(range(i)):
        sub = p_list[i] - p_list[j]
        add = p_list[j] + p_list[i]
        if inv_P(sub) and inv_P(add):
            end = time.time()
            print(i, j)
            print(sub)
            print(end - start)
            exit()
