# <p>Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:</p>
# <table><tr><td>Triangle</td>
# <td> </td>
# <td>$T_n=n(n+1)/2$</td>
# <td> </td>
# <td>$1, 3, 6, 10, 15, \dots$</td>
# </tr><tr><td>Pentagonal</td>
# <td> </td>
# <td>$P_n=n(3n - 1)/2$</td>
# <td> </td>
# <td>$1, 5, 12, 22, 35, \dots$</td>
# </tr><tr><td>Hexagonal</td>
# <td> </td>
# <td>$H_n=n(2n - 1)$</td>
# <td> </td>
# <td>$1, 6, 15, 28, 45, \dots$</td>
# </tr></table><p>It can be verified that $T_{285} = P_{165} = H_{143} = 40755$.</p>
# <p>Find the next triangle number that is also pentagonal and hexagonal.</p>

from math import sqrt
import time

def inv_P(p):
    return (1 + sqrt(1+24*p)) % 6 == 0

# def inv_T(t):
#     return (sqrt(1 + 8*t) - 1) % 2 == 0

def H(n):
    return n * (2 * n - 1)

start = time.time()
h = 144
while True:
    num = H(h)
    if inv_P(num): # Hex-num is always a Tri-num (t=2h-1)
        print(num)
        break
    h += 1
end = time.time()
print(end-start)
