# <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
# $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
# <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

sum = 2
a = 1
b = 2
new_term = 0
while new_term < 4_000_000:

    new_term = a + b
    if new_term % 2 == 0:
        sum += new_term
    a = b
    b = new_term

print(sum)
